# Generated by Django 5.2.6 on 2025-09-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('close_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'btc_prices',
                'ordering': ['-open_time'],
                'indexes': [models.Index(fields=['open_time'], name='btc_prices_open_ti_bb0021_idx'), models.Index(fields=['close_time'], name='btc_prices_close_t_f74cb7_idx')],
            },
        ),
    ]
