# Generated by Django 5.2.6 on 2025-09-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pricealert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricealert',
            name='user',
        ),
        migrations.AddField(
            model_name='pricealert',
            name='email',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
