# Generated by Django 5.2.6 on 2025-09-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_pricealert_user_pricealert_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETHline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('close_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'eth_prices',
                'ordering': ['-open_time'],
                'indexes': [models.Index(fields=['open_time'], name='eth_prices_open_ti_119e5d_idx'), models.Index(fields=['close_time'], name='eth_prices_close_t_49c114_idx')],
            },
        ),
    ]
