# Generated by Django 5.2.6 on 2025-09-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ethline'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='crypto',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], default='BTC', max_length=3),
        ),
    ]
