# Generated by Django 5.2.6 on 2025-09-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_pricealert_crypto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricealert',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
